{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.3.0.jar",
          "url": "versiont-library-1.3.0.jar",
          "size": 8024592,
          "sha512": "682d7b1ace281aa680a0a6224fa287573aa5d0313b9b463fa85257ae4705bf91dba4e9375027b859cc060efff5becec3a5e3199f126c6eb84e872a37e477157f",
          "sha256": "70a6444da5e471b445007ffdd3c4f7f7eaf2fe135791308ee0de42937b44ceed",
          "sha1": "dfe8af3e3283cc12045d73cad3f40110f8f72f38",
          "md5": "387bcc81885aa64f7b8f33ffc1c37751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.2"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.3.0.jar",
          "url": "versiont-library-1.3.0.jar",
          "size": 8024592,
          "sha512": "682d7b1ace281aa680a0a6224fa287573aa5d0313b9b463fa85257ae4705bf91dba4e9375027b859cc060efff5becec3a5e3199f126c6eb84e872a37e477157f",
          "sha256": "70a6444da5e471b445007ffdd3c4f7f7eaf2fe135791308ee0de42937b44ceed",
          "sha1": "dfe8af3e3283cc12045d73cad3f40110f8f72f38",
          "md5": "387bcc81885aa64f7b8f33ffc1c37751"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.3.0-sources.jar",
          "url": "versiont-library-1.3.0-sources.jar",
          "size": 81594,
          "sha512": "caadef4095fce02ff8b649fab48f6a9e4658b434ba397396199a44f79880efb4a98735dfd933b192cd1dc57cb653f68c7fcab99c21c50d1d1bdb79539df2a23a",
          "sha256": "ed42b8e05223adf2387fa46a84f088ae2681c4b365f0f3a44fac066c672ebd11",
          "sha1": "bf7209d6f561a5f95d419b22ed75777e17977935",
          "md5": "1d4ee375ebe7f74740b11150c6c927c2"
        }
      ]
    }
  ]
}
