{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.2.2.jar",
          "url": "versiont-library-1.2.2.jar",
          "size": 8022415,
          "sha512": "6b746da187b21934f1075c51006c7cead90b9e2d4a417c23a83cb3707f23bf45c750680b4c54ce9e80c5ecc8e1ec6449041e0beabf22903dac937e852e6367da",
          "sha256": "0c9d7c71250dbdcfa8dd2c4ae04cc284037736f9ee3240059857ea2e542a5bf6",
          "sha1": "213d16c059900c49bbe29c0607880991b8febb1f",
          "md5": "9d53ea00754fe57ff6ebfe716a294993"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.2.2.jar",
          "url": "versiont-library-1.2.2.jar",
          "size": 8022415,
          "sha512": "6b746da187b21934f1075c51006c7cead90b9e2d4a417c23a83cb3707f23bf45c750680b4c54ce9e80c5ecc8e1ec6449041e0beabf22903dac937e852e6367da",
          "sha256": "0c9d7c71250dbdcfa8dd2c4ae04cc284037736f9ee3240059857ea2e542a5bf6",
          "sha1": "213d16c059900c49bbe29c0607880991b8febb1f",
          "md5": "9d53ea00754fe57ff6ebfe716a294993"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.2.2-sources.jar",
          "url": "versiont-library-1.2.2-sources.jar",
          "size": 81025,
          "sha512": "e5537fd5a904e8341791c93247d10f093d76a96fdb7c7261d7a7992dba037f3ff50ac2c1c2be65eb9d91794d521ad16d8be88c6e2cbd80346eeef438b31c9d91",
          "sha256": "7d999390bfaab0907e6e5ee52a7b489b689e182e78c71a6ac5cfab50e94c47f4",
          "sha1": "eafcce25fdde2dc124a7ce8b2055fa4ac874fce8",
          "md5": "ff2d0d93308830c729ddf683d1eda452"
        }
      ]
    }
  ]
}
