{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-0.0.5.jar",
          "url": "versiont-library-0.0.5.jar",
          "size": 8016615,
          "sha512": "556b2794d005975fd48686c13ce73224eb61e08e77cdb1cee6776c43446d2e0ee14ded4f2d6506b9899d8e5b251b06abf9a67c4e08a8776fed46bd5b70df326e",
          "sha256": "b0aae3710f490b5acadfe75e437e0a9775175e45e084af3dad0b7ea6f0b3bec2",
          "sha1": "15e10a32d1e877679776635f24a4a3394abd193a",
          "md5": "a7ea0f1e1e98dc0bb8768493e4c4b593"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-0.0.5.jar",
          "url": "versiont-library-0.0.5.jar",
          "size": 8016615,
          "sha512": "556b2794d005975fd48686c13ce73224eb61e08e77cdb1cee6776c43446d2e0ee14ded4f2d6506b9899d8e5b251b06abf9a67c4e08a8776fed46bd5b70df326e",
          "sha256": "b0aae3710f490b5acadfe75e437e0a9775175e45e084af3dad0b7ea6f0b3bec2",
          "sha1": "15e10a32d1e877679776635f24a4a3394abd193a",
          "md5": "a7ea0f1e1e98dc0bb8768493e4c4b593"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-0.0.5-sources.jar",
          "url": "versiont-library-0.0.5-sources.jar",
          "size": 78638,
          "sha512": "a62902f37a6a3bea21cf82f261cd7bb6386c9f65981599711e60806c2093e5ece391334fee0f18cd3ae7c0bd45de5e169cfe59436ca508b4975d449ebd052e2e",
          "sha256": "6ce97be8e8f823945798aa7f523907aaf94da774e0d4de0dda7bd9503cece1e8",
          "sha1": "e6b64c03910ac8552afb6974b1cc41eceea914cf",
          "md5": "177b54774069ff6003876ca94269f82f"
        }
      ]
    }
  ]
}
