{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.5.jar",
          "url": "versiont-toolchain-0.0.5.jar",
          "size": 27334,
          "sha512": "f7183d40fb22da759485665ca8f6eb6590eaf78d2f1643436370e1d9f39b0f355e8d7f72aef1adae882be07878dcd06e3b74a36eba91a20e83038f51526ed55e",
          "sha256": "6acf171e77e3e2570f24eb6337aaa0fa438bcbd422c384e37c115d294c282d1f",
          "sha1": "21a567c3151c52a51f779e94335e087bcda5b573",
          "md5": "37922eed6db2d6a5b4b5b99e66cea93c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.5.jar",
          "url": "versiont-toolchain-0.0.5.jar",
          "size": 27334,
          "sha512": "f7183d40fb22da759485665ca8f6eb6590eaf78d2f1643436370e1d9f39b0f355e8d7f72aef1adae882be07878dcd06e3b74a36eba91a20e83038f51526ed55e",
          "sha256": "6acf171e77e3e2570f24eb6337aaa0fa438bcbd422c384e37c115d294c282d1f",
          "sha1": "21a567c3151c52a51f779e94335e087bcda5b573",
          "md5": "37922eed6db2d6a5b4b5b99e66cea93c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.5-javadoc.jar",
          "url": "versiont-toolchain-0.0.5-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.5-sources.jar",
          "url": "versiont-toolchain-0.0.5-sources.jar",
          "size": 8223,
          "sha512": "302a9ebf9c24e3d79b9158704c20cb5f1522bc3ac5f4019c04e9b48590bf5cf4517c552fec96a8038b5553dc77a27f293138c1cd2eb23d8d0d2f49c05fb63520",
          "sha256": "6c7f1621003312eda44381359627a0c0a9362d68563e8e026895657e1c8354d2",
          "sha1": "6d84947eb06d45d299200d6470e80be932f7a3b5",
          "md5": "b426522fde94033f867db3411358420f"
        }
      ]
    }
  ]
}
