{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.6.jar",
          "url": "versiont-toolchain-1.3.6.jar",
          "size": 27585,
          "sha512": "b5297e92bfa3163754ecc55e9cdad90bf6792bf004360477570f1f9ffcbc04afa8304a78bd6cc844a9a649e8be92747d4a53787844a2fa03b155e80ea0ccc7e9",
          "sha256": "d1a3e64cd101fbec8d5402621d7759be80aa720e1372b1728dca47aa5a18c08a",
          "sha1": "1e7a242cc0f965af6d4a0a1ae2e035b239b228c4",
          "md5": "7a62254ef08dd60455ed04d7938f041b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.6.jar",
          "url": "versiont-toolchain-1.3.6.jar",
          "size": 27585,
          "sha512": "b5297e92bfa3163754ecc55e9cdad90bf6792bf004360477570f1f9ffcbc04afa8304a78bd6cc844a9a649e8be92747d4a53787844a2fa03b155e80ea0ccc7e9",
          "sha256": "d1a3e64cd101fbec8d5402621d7759be80aa720e1372b1728dca47aa5a18c08a",
          "sha1": "1e7a242cc0f965af6d4a0a1ae2e035b239b228c4",
          "md5": "7a62254ef08dd60455ed04d7938f041b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.6-javadoc.jar",
          "url": "versiont-toolchain-1.3.6-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.6-sources.jar",
          "url": "versiont-toolchain-1.3.6-sources.jar",
          "size": 8490,
          "sha512": "b0b2f7023b08f5d3f99ee4147997226e1b6b912fe29e22837a92d20ed194eedaa7d26b0c2cf96f51946f4429b3bf13bee81f03b306539b3d20bb9783a363cee3",
          "sha256": "5ea1cca01a8910337ee185d7f34b5300f820bbdb1ce1b3a136d8a39890d05a99",
          "sha1": "f24af2c5126ec1e5936ec96cf65afbd2730ad5bb",
          "md5": "ba934dae370cd42a1723e09bb865195a"
        }
      ]
    }
  ]
}
