{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.5.jar",
          "url": "versiont-toolchain-1.3.5.jar",
          "size": 27452,
          "sha512": "26e6dd5d05f9ec0e32fa9dafc9801e80d43d9ff9b5e107810eb20bc9eae4cd1d9240f8a2f96ec3d3adaea7aebef36418e54bf0c07b66eeb789e95a1d42b25b2f",
          "sha256": "2986031a05e40ae0de18811c825a58af00d6ec7c033189f50ad38d979731dfa8",
          "sha1": "de4560bc01016365b5aecb5f15ab6a1e7e373c63",
          "md5": "cff41893f5119b7dec91d767366e77e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.5.jar",
          "url": "versiont-toolchain-1.3.5.jar",
          "size": 27452,
          "sha512": "26e6dd5d05f9ec0e32fa9dafc9801e80d43d9ff9b5e107810eb20bc9eae4cd1d9240f8a2f96ec3d3adaea7aebef36418e54bf0c07b66eeb789e95a1d42b25b2f",
          "sha256": "2986031a05e40ae0de18811c825a58af00d6ec7c033189f50ad38d979731dfa8",
          "sha1": "de4560bc01016365b5aecb5f15ab6a1e7e373c63",
          "md5": "cff41893f5119b7dec91d767366e77e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.5-javadoc.jar",
          "url": "versiont-toolchain-1.3.5-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.5-sources.jar",
          "url": "versiont-toolchain-1.3.5-sources.jar",
          "size": 8357,
          "sha512": "49a88ba6a30d481ce7f0efffd5370c02ee4582fa231b8cc43dae9219b712f0ef7870b69edcd51bbb308b426d0a1d8506d2aad2ee55a180d3b435194929299b6e",
          "sha256": "a33c9ffc989139532139838ec83eacd33a0f3de97029b7d8103d63b3decbb8e5",
          "sha1": "fc0ef289a3d80ebae626c271ed493419c82bcb61",
          "md5": "128e4813bd9a2d238038e41eabf50f6c"
        }
      ]
    }
  ]
}
