{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.8.jar",
          "url": "versiont-toolchain-1.3.8.jar",
          "size": 27593,
          "sha512": "ec2fda1a8034fa51f0a39234ae68380398ba4e0c0141fe6491909f75081c5373feb3c88aae649d96fd227d852c1400aa1b51bc909baeb01953379f3e2bc60c1c",
          "sha256": "ff609c6bc8db0846f9757302e78efeaa31e3d7b5109b9d43d65e1c84fabbe5e6",
          "sha1": "ace3932c758b9a0111689946f834b7b5139f6530",
          "md5": "03f416ba2d65d22b3bd4ef981edd1f1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.8.jar",
          "url": "versiont-toolchain-1.3.8.jar",
          "size": 27593,
          "sha512": "ec2fda1a8034fa51f0a39234ae68380398ba4e0c0141fe6491909f75081c5373feb3c88aae649d96fd227d852c1400aa1b51bc909baeb01953379f3e2bc60c1c",
          "sha256": "ff609c6bc8db0846f9757302e78efeaa31e3d7b5109b9d43d65e1c84fabbe5e6",
          "sha1": "ace3932c758b9a0111689946f834b7b5139f6530",
          "md5": "03f416ba2d65d22b3bd4ef981edd1f1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.8-javadoc.jar",
          "url": "versiont-toolchain-1.3.8-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.8-sources.jar",
          "url": "versiont-toolchain-1.3.8-sources.jar",
          "size": 8498,
          "sha512": "7843ffc1fadf561e0569c407cd6df2bf646b3f9e3c58bd0356b16c2f4a12c3bf65ce4aa2b412839bd6690fbd82e891b135d84e3c02fff9f5576fc31c6587ea43",
          "sha256": "90a923bebf99bcc8fe966d43bfef77a404e0d208bc9d5f8ef12b29c165245b81",
          "sha1": "ffd6e62aa33f22993f363fdd8ef58d2ce09735f8",
          "md5": "14dd24252f50218a67cd0d919e9bd080"
        }
      ]
    }
  ]
}
