{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.4.jar",
          "url": "versiont-toolchain-1.3.4.jar",
          "size": 27437,
          "sha512": "a3bf1d2a9b9a6f8bf3d92949a219c116a978b0e24cbc6f8412df34c83d46051b60a1a1402e7446405755f57ed323265c7b36ae0bbabcb8aa78c01748b51621b8",
          "sha256": "a2e4673a0c1879ded360bf344dc5d2f36fa58b513193de90aa0d7832b353e8d6",
          "sha1": "ef3bff94a53ef62a0b4706a07abbe51f2696147e",
          "md5": "dd2ead6083f7d2c8e001abe01e39cc6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.4.jar",
          "url": "versiont-toolchain-1.3.4.jar",
          "size": 27437,
          "sha512": "a3bf1d2a9b9a6f8bf3d92949a219c116a978b0e24cbc6f8412df34c83d46051b60a1a1402e7446405755f57ed323265c7b36ae0bbabcb8aa78c01748b51621b8",
          "sha256": "a2e4673a0c1879ded360bf344dc5d2f36fa58b513193de90aa0d7832b353e8d6",
          "sha1": "ef3bff94a53ef62a0b4706a07abbe51f2696147e",
          "md5": "dd2ead6083f7d2c8e001abe01e39cc6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.4-javadoc.jar",
          "url": "versiont-toolchain-1.3.4-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.4-sources.jar",
          "url": "versiont-toolchain-1.3.4-sources.jar",
          "size": 8343,
          "sha512": "4344d2df2a2d3844324a141aaf64fb23fda41da1ca4f261aae6c2e62718a1eaaf48e9fd504c5947c01da4bb7bedd4a4bc4bc17e0223d0e91678c25f5cceb891b",
          "sha256": "a6f78105eaf3169d5a09ac35e518c69e1e1aac2e7e2c513653814d726e7fc7aa",
          "sha1": "d8c4cc9056ef0305c7b81c13ec62c85cb5d76e04",
          "md5": "ed0e7caf3f036f34d98d47e210464cf1"
        }
      ]
    }
  ]
}
