{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.7.jar",
          "url": "versiont-toolchain-0.0.7.jar",
          "size": 27341,
          "sha512": "c3ebf474ee5e29c46ffd7ad2189ad354fa86ccd02d4cd26450c311188535ae5ad96df441ac31ea41e661181e9ee81d71d6a825a6e7e215067417104e2ef39910",
          "sha256": "7ca0a23fc9a9dd4258033fb09736f0f2056bb5e0912a72322b1f4337ed9da8f3",
          "sha1": "cfd311e1ec2f7c68af8817e3455952ce02a97096",
          "md5": "ecb98a71e99f5174b5f29d03ecd0068f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.7.jar",
          "url": "versiont-toolchain-0.0.7.jar",
          "size": 27341,
          "sha512": "c3ebf474ee5e29c46ffd7ad2189ad354fa86ccd02d4cd26450c311188535ae5ad96df441ac31ea41e661181e9ee81d71d6a825a6e7e215067417104e2ef39910",
          "sha256": "7ca0a23fc9a9dd4258033fb09736f0f2056bb5e0912a72322b1f4337ed9da8f3",
          "sha1": "cfd311e1ec2f7c68af8817e3455952ce02a97096",
          "md5": "ecb98a71e99f5174b5f29d03ecd0068f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.7-javadoc.jar",
          "url": "versiont-toolchain-0.0.7-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-0.0.7-sources.jar",
          "url": "versiont-toolchain-0.0.7-sources.jar",
          "size": 8230,
          "sha512": "fce3c9b4f6e16a838f2c3c57aad57e4ac74f4071bf72ea5568077441bc96015051d45367d1f9f886cc5f0faeb72c3695fef6b7be04464d6bcaf62d063105bf18",
          "sha256": "a5760ded5c8daa7c9de00d62f34b010b62241603f94395a9a11e3cf0d4d9ab87",
          "sha1": "1f0602309cf098cf3936a7aa70c7d49a50f32e37",
          "md5": "a74bffcfbe0e088a0bfd6ca07f46f767"
        }
      ]
    }
  ]
}
