{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.2.3.jar",
          "url": "versiont-library-1.2.3.jar",
          "size": 8023086,
          "sha512": "7724e1dc572739ab3385e2d6d89d2057c02b76904fd62d7096c41bce7f4fea0480e1ea5a3fffa175f9c747171ea9c209d798be6ee6b357c99bde746abd31d01c",
          "sha256": "f3f97135602381872f2c03ea17bbcfe6ddaea88de501ffb334ce7da4bf7d5bcc",
          "sha1": "433eec53f76b621137de8b505d30007a0ea1df36",
          "md5": "4355068117727979910ab879aaf46cad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.2.3.jar",
          "url": "versiont-library-1.2.3.jar",
          "size": 8023086,
          "sha512": "7724e1dc572739ab3385e2d6d89d2057c02b76904fd62d7096c41bce7f4fea0480e1ea5a3fffa175f9c747171ea9c209d798be6ee6b357c99bde746abd31d01c",
          "sha256": "f3f97135602381872f2c03ea17bbcfe6ddaea88de501ffb334ce7da4bf7d5bcc",
          "sha1": "433eec53f76b621137de8b505d30007a0ea1df36",
          "md5": "4355068117727979910ab879aaf46cad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.2.3-sources.jar",
          "url": "versiont-library-1.2.3-sources.jar",
          "size": 81211,
          "sha512": "9057cd01489adcc1126e5495d73662275be63173ced6a11c4cd54fbec280a48d05a430d9cfa1e87b397c0506afbcf63be7109652fff0589b5fd2030053ed455c",
          "sha256": "bcf45f7b9ca111da8779882810ad7823fb067026fb98feeb5727c54b3a03fe9b",
          "sha1": "85dea6cbb940f62abbe5faf68e6b4bebe250ebf6",
          "md5": "c9baf6000e4cdadfc0bd18587387e93b"
        }
      ]
    }
  ]
}
