{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.0.2.jar",
          "url": "versiont-toolchain-1.0.2.jar",
          "size": 27433,
          "sha512": "bd975755f94ee331caa058bc7ded6de0b2c4f0e92d18670de39841f0d77daf536a8f588f6f6acdf29de4b9d4844782f6eff6279ddd3638024598739fdd84dc74",
          "sha256": "e855b3a196222fe48588b3c1c745fd9fcef51715b2298fe9bba13d6a9aaf4782",
          "sha1": "c788ec867d95f7106f59e9bb26190cb345779f26",
          "md5": "ae91a7e629ce1ef01a3ab4d8ca07b3e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.0.2.jar",
          "url": "versiont-toolchain-1.0.2.jar",
          "size": 27433,
          "sha512": "bd975755f94ee331caa058bc7ded6de0b2c4f0e92d18670de39841f0d77daf536a8f588f6f6acdf29de4b9d4844782f6eff6279ddd3638024598739fdd84dc74",
          "sha256": "e855b3a196222fe48588b3c1c745fd9fcef51715b2298fe9bba13d6a9aaf4782",
          "sha1": "c788ec867d95f7106f59e9bb26190cb345779f26",
          "md5": "ae91a7e629ce1ef01a3ab4d8ca07b3e9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.0.2-javadoc.jar",
          "url": "versiont-toolchain-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.0.2-sources.jar",
          "url": "versiont-toolchain-1.0.2-sources.jar",
          "size": 8338,
          "sha512": "b06acb63908d95745d4e61ed667ab3b579253622e80355138d0e439feb47ac58e6715239ee7006da9bd682b7249072be86c0083f4bb30ad13ff0041c97dfce45",
          "sha256": "2b7a310aed099854b51c94a3fab771d7dba4dd737b32dc9d45025082c310ef07",
          "sha1": "f3c3003a453a20c450b754719d99d992d39a3a96",
          "md5": "615bf868aedbff66390afd03c069e6f2"
        }
      ]
    }
  ]
}
