{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.3.2.jar",
          "url": "versiont-library-1.3.2.jar",
          "size": 8027945,
          "sha512": "43cf2c4e69205151123bef4769735e3a2259255e0f552a7804c37db7b5bd2220c18a4316f3f77c8c1b4f2850124fc42e7efd2c29222cdc89cb149cf81b63266a",
          "sha256": "73790f2e78a942d963dbb0940731257d4bde92edb35eb1e99f91625f5af5c750",
          "sha1": "b9cec52bd45dc9c8bb76c3311bbff583d43cd35e",
          "md5": "2796a343c48a9ba9c334342def93e299"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.2"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.3.2.jar",
          "url": "versiont-library-1.3.2.jar",
          "size": 8027945,
          "sha512": "43cf2c4e69205151123bef4769735e3a2259255e0f552a7804c37db7b5bd2220c18a4316f3f77c8c1b4f2850124fc42e7efd2c29222cdc89cb149cf81b63266a",
          "sha256": "73790f2e78a942d963dbb0940731257d4bde92edb35eb1e99f91625f5af5c750",
          "sha1": "b9cec52bd45dc9c8bb76c3311bbff583d43cd35e",
          "md5": "2796a343c48a9ba9c334342def93e299"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.3.2-sources.jar",
          "url": "versiont-library-1.3.2-sources.jar",
          "size": 83291,
          "sha512": "4440e4552276fb231a78208ffbdb67f97fcf74e385e453b67c5ba99daefeb32c78cc6c7bcdf7f7f334d720a5aa1a259a6457d7453df776d32753c67a98fdb3d3",
          "sha256": "3576fd034ee7f52262dd00b0d566b1af1ad4908d872e70958fd4a7747fa0701c",
          "sha1": "1f4bfce352431559e1ada37f5ae8b86b860cfcd4",
          "md5": "5dcbecea5e3b004e1ca5178d983e752f"
        }
      ]
    }
  ]
}
