{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-0.0.7.jar",
          "url": "versiont-library-0.0.7.jar",
          "size": 8016695,
          "sha512": "6f44546b9e5fe72542b4183d22f59a37e9ef2950d47e7c7cfa8baa6290f7f643d7050aa8ddbd053e13af539c0effdeff04246e630d4abecbc8ca85370eea9858",
          "sha256": "a10570025cb2e96307cd9350b76f6ae3fb91df032a7e9ae158099e495fadd478",
          "sha1": "7ca293361406955e9d13e005ed1f8a024df4a620",
          "md5": "9520e23ee559da6f3fc08a028c0606de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-0.0.7.jar",
          "url": "versiont-library-0.0.7.jar",
          "size": 8016695,
          "sha512": "6f44546b9e5fe72542b4183d22f59a37e9ef2950d47e7c7cfa8baa6290f7f643d7050aa8ddbd053e13af539c0effdeff04246e630d4abecbc8ca85370eea9858",
          "sha256": "a10570025cb2e96307cd9350b76f6ae3fb91df032a7e9ae158099e495fadd478",
          "sha1": "7ca293361406955e9d13e005ed1f8a024df4a620",
          "md5": "9520e23ee559da6f3fc08a028c0606de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-0.0.7-sources.jar",
          "url": "versiont-library-0.0.7-sources.jar",
          "size": 78657,
          "sha512": "ba1da3d655b07f6a170ba0222127ad802304155f25b52a596192c0e30e3d7e1ae74556b9f6949fcabaa682498d6d10c715833cc6dfc343a8c01334a02e899806",
          "sha256": "d37428c116fa4767b8e79558c3979b9c6e0d67d09186a383bb8ee695fccc72da",
          "sha1": "338cf694c6e30b101ff4613f9073cbefc04b5eef",
          "md5": "9e6461518b8037026e2b2f3744d93842"
        }
      ]
    }
  ]
}
