{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.9.jar",
          "url": "versiont-toolchain-1.3.9.jar",
          "size": 28942,
          "sha512": "ed578cdc4498e346e3f1eb33d5d871f12218f31e0b01f856eaf7ea2737d62edc5a1bfa579e7109e90f6454be252a7078ef0784fa2d7db4f52ac63fd853cd2063",
          "sha256": "15c63895d21e2796ce1f9ed7e3d3bf33ee357383aae27ed24aeb73a59d642bb9",
          "sha1": "c7454421cd3ea724c3a36589a5b669d627edb96d",
          "md5": "80eff033c39018e3f777bc5e9ac6eb3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.9.jar",
          "url": "versiont-toolchain-1.3.9.jar",
          "size": 28942,
          "sha512": "ed578cdc4498e346e3f1eb33d5d871f12218f31e0b01f856eaf7ea2737d62edc5a1bfa579e7109e90f6454be252a7078ef0784fa2d7db4f52ac63fd853cd2063",
          "sha256": "15c63895d21e2796ce1f9ed7e3d3bf33ee357383aae27ed24aeb73a59d642bb9",
          "sha1": "c7454421cd3ea724c3a36589a5b669d627edb96d",
          "md5": "80eff033c39018e3f777bc5e9ac6eb3f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.9-javadoc.jar",
          "url": "versiont-toolchain-1.3.9-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.9-sources.jar",
          "url": "versiont-toolchain-1.3.9-sources.jar",
          "size": 8524,
          "sha512": "f034b72e89ff20fb74c1176372fc928f104b8d3fa8c99f9c8c302ec712d75ab91f843dc5ed07f11a3776ed86af45258b4f1991cfc880259e321085c8eb91f9f8",
          "sha256": "b3c90b8d713ce6785e73f797909076089f8003b1cf9e13a32493563e30b64b62",
          "sha1": "da6d2b3095da9cca0ddff985ade3fd3fb7f8a86b",
          "md5": "b93f6a447f7f84b664fc63158a606c2e"
        }
      ]
    }
  ]
}
