{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.0.jar",
          "url": "versiont-toolchain-1.3.0.jar",
          "size": 27438,
          "sha512": "95ea9bbd7ed822a50672b6efa29bb5d2ff0ddc2bf0618af5c2579c7f153f3c0e20e95a96bc2d72f41b32d1f845fc887212934daf07758e5d9f8f8f9e08b2a62b",
          "sha256": "3871f59a6d13834f99817fd5041e8bef6c410f1a885ab5d9f06213a287b7ffe7",
          "sha1": "0f295efd9687075fa1a27ecd84643195d40ef60b",
          "md5": "1a6fca9ea18f4eeeb72273d117089a81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.0.jar",
          "url": "versiont-toolchain-1.3.0.jar",
          "size": 27438,
          "sha512": "95ea9bbd7ed822a50672b6efa29bb5d2ff0ddc2bf0618af5c2579c7f153f3c0e20e95a96bc2d72f41b32d1f845fc887212934daf07758e5d9f8f8f9e08b2a62b",
          "sha256": "3871f59a6d13834f99817fd5041e8bef6c410f1a885ab5d9f06213a287b7ffe7",
          "sha1": "0f295efd9687075fa1a27ecd84643195d40ef60b",
          "md5": "1a6fca9ea18f4eeeb72273d117089a81"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.0-javadoc.jar",
          "url": "versiont-toolchain-1.3.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.0-sources.jar",
          "url": "versiont-toolchain-1.3.0-sources.jar",
          "size": 8343,
          "sha512": "033e24eecc9defe02f0339df6029ba294c239ae736d1c18deb5ff09f095d5ae7b7dce07af73105a55a0fa05310c17c3e7e1d78659764f2b70a2e6a629a5237ea",
          "sha256": "5b6e45ab5f05aa4b7569db4776640d4abe18ef7daa21667c2ff1a53411497730",
          "sha1": "85856c548ca3d773050b9da0fa99ab77701c8d66",
          "md5": "bf81b8b8a239d2e299676c3d0cbc0739"
        }
      ]
    }
  ]
}
