{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.0.0.jar",
          "url": "versiont-library-1.0.0.jar",
          "size": 8016744,
          "sha512": "4b225f41eed6a7103add70e53df1b5a8a4c962a3dee9a7cd06f0cdf98921507aeec4f303520634278613d8928408e028c4ad9ebd84acae8eaab281b5a0f82766",
          "sha256": "be095a1b6e7a7a62ef744338982384b14b28fcace0c2d2802b04b931481c648b",
          "sha1": "689a1c80f77228baa99e2f94b5a4f161149b0cf9",
          "md5": "ab7aa0d8ff016d4d088c376071f2ad13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.0.0.jar",
          "url": "versiont-library-1.0.0.jar",
          "size": 8016744,
          "sha512": "4b225f41eed6a7103add70e53df1b5a8a4c962a3dee9a7cd06f0cdf98921507aeec4f303520634278613d8928408e028c4ad9ebd84acae8eaab281b5a0f82766",
          "sha256": "be095a1b6e7a7a62ef744338982384b14b28fcace0c2d2802b04b931481c648b",
          "sha1": "689a1c80f77228baa99e2f94b5a4f161149b0cf9",
          "md5": "ab7aa0d8ff016d4d088c376071f2ad13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.0.0-sources.jar",
          "url": "versiont-library-1.0.0-sources.jar",
          "size": 78690,
          "sha512": "bf29cc0d372f00fd207e68080faf55ad33396430f82f1da15574d1264a2b78edc8023f6096618ec553d74c526fa760252c3be12cc2de8eb47d00f1bc82f97882",
          "sha256": "fadd83c569b63482583e51ce8ec8f99a0078d456558e94cb906ea00b3f772223",
          "sha1": "4ec3db7b713f9fe413a89006eea8062321b842e4",
          "md5": "efdcbc77f8d9db524ec91d0a8158f380"
        }
      ]
    }
  ]
}
