{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.2.1.jar",
          "url": "versiont-library-1.2.1.jar",
          "size": 8022404,
          "sha512": "0cc92204779e22b803aa07059c99359dc775db80d63201774fc1201c2ccc849724434fc97bf88a8e21b750f78e3281bbe67463b1eb2a67a0fa67f275fd008990",
          "sha256": "841c8016c0ef4ade94f27478d3fc22bb64041cc182ae7b1fdf01b8305233c796",
          "sha1": "49cfde4b9fa561f2bf54b10c5562351864c0671b",
          "md5": "38304e291c02cbabcd4983c29ceb4def"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.6"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.1"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.2.1.jar",
          "url": "versiont-library-1.2.1.jar",
          "size": 8022404,
          "sha512": "0cc92204779e22b803aa07059c99359dc775db80d63201774fc1201c2ccc849724434fc97bf88a8e21b750f78e3281bbe67463b1eb2a67a0fa67f275fd008990",
          "sha256": "841c8016c0ef4ade94f27478d3fc22bb64041cc182ae7b1fdf01b8305233c796",
          "sha1": "49cfde4b9fa561f2bf54b10c5562351864c0671b",
          "md5": "38304e291c02cbabcd4983c29ceb4def"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.2.1-sources.jar",
          "url": "versiont-library-1.2.1-sources.jar",
          "size": 81014,
          "sha512": "2ad1e6f797ed52ec9420b9f5437c8e573512375b12c5536a0964457121290a8b95d20ad3bc1fdf3a45db7c939c8e38e2aebda649f03e6662f72c4069ee05d77d",
          "sha256": "8237d7b8cdaf37dbd63e05d114a3a9a4343b3d134829bdef52866b8be514dd93",
          "sha1": "e66ded324350d383b540a132976d55a8b95034bf",
          "md5": "07bf2023a0fff7211ca9c43b4952e382"
        }
      ]
    }
  ]
}
