{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-library",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-library-1.3.1.jar",
          "url": "versiont-library-1.3.1.jar",
          "size": 8027736,
          "sha512": "0b6a23e44eac7fc49a9d6c8be799f7fb11f9210f01c21f18c8b2adf73b84b620f0ce0af3773c22c2f5b79701e5127b1a3ae4c82afe3ca1c661148392e516caed",
          "sha256": "eb39be2f6f180e61592673a6bd463d8a8b3a5593abf9c95b0b16b21126c79f2d",
          "sha1": "0e0b989261857dfc8010191d13c324398b383750",
          "md5": "4f910797091ed268354d15e50e96041b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.2"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.4"
          }
        }
      ],
      "files": [
        {
          "name": "versiont-library-1.3.1.jar",
          "url": "versiont-library-1.3.1.jar",
          "size": 8027736,
          "sha512": "0b6a23e44eac7fc49a9d6c8be799f7fb11f9210f01c21f18c8b2adf73b84b620f0ce0af3773c22c2f5b79701e5127b1a3ae4c82afe3ca1c661148392e516caed",
          "sha256": "eb39be2f6f180e61592673a6bd463d8a8b3a5593abf9c95b0b16b21126c79f2d",
          "sha1": "0e0b989261857dfc8010191d13c324398b383750",
          "md5": "4f910797091ed268354d15e50e96041b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-library-1.3.1-sources.jar",
          "url": "versiont-library-1.3.1-sources.jar",
          "size": 83256,
          "sha512": "891349bbcbf4e1e34fe09d111b7cf435b56695e07aa0f548b0d7ae15389adda80b784fa9d08df67c5acfbea049a2bd55c60fe938a2ad402387be46001d36ace0",
          "sha256": "952dcf3e142a87b68d2d7055c8afb4bf3f0c99cb99f46bced413eaf8e4bd9d10",
          "sha1": "eb42dd59f4d8bb49fbec94738b7f21afe34731e6",
          "md5": "50fe68d3c0136c2491824720fff10649"
        }
      ]
    }
  ]
}
