{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.2.0.jar",
          "url": "versiont-toolchain-1.2.0.jar",
          "size": 27433,
          "sha512": "223b6823b046c79edbf03f90b3c66665af1cd4ad4f2833ba7c987f11b7aa844bbbd70772c55816664836bb8b723f410db50799bbd651e0c8a847327e144c23f8",
          "sha256": "c6d661a0a2fce86aba17d792c45c47ad9dec004973ec8712d8f43041b12c7f6d",
          "sha1": "7da928b818e4e5ad609ded7bcf9c1ad57cc698af",
          "md5": "d08ddf676a51dab3661d6bf361f0e352"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.2.0.jar",
          "url": "versiont-toolchain-1.2.0.jar",
          "size": 27433,
          "sha512": "223b6823b046c79edbf03f90b3c66665af1cd4ad4f2833ba7c987f11b7aa844bbbd70772c55816664836bb8b723f410db50799bbd651e0c8a847327e144c23f8",
          "sha256": "c6d661a0a2fce86aba17d792c45c47ad9dec004973ec8712d8f43041b12c7f6d",
          "sha1": "7da928b818e4e5ad609ded7bcf9c1ad57cc698af",
          "md5": "d08ddf676a51dab3661d6bf361f0e352"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.2.0-javadoc.jar",
          "url": "versiont-toolchain-1.2.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.2.0-sources.jar",
          "url": "versiont-toolchain-1.2.0-sources.jar",
          "size": 8338,
          "sha512": "fb5a85e9b276dacf3aa19f832d64de689f65a450560a74b9673d475caa38cfcd467ef738e82667d7fe46115dc4d87a08b3eb2466b41e9a9e46c1c5db6b4af72a",
          "sha256": "c02155c4286a5f480ee7636d194bdc9962377a0616f97518d16782c2a3eb5e01",
          "sha1": "c90a05dd256e8a93ac5c9bc2f340f3eb085740fb",
          "md5": "95808f56552cd93d56f9e5faa8210840"
        }
      ]
    }
  ]
}
