{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.gxlg",
    "module": "versiont-toolchain",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.1.jar",
          "url": "versiont-toolchain-1.3.1.jar",
          "size": 27465,
          "sha512": "4ec25a6d17e6a714c848dbbf4950451fee3ebf74af45312080a87a9c43e03b1a48c31a746434b82852776fa757b9cabc2246c16e8e1309e6fed461f7783fb9a0",
          "sha256": "c332efe2c4f9b600e56964e59c683be1209f8b342798bbc48cfc5eef7cfd5d6d",
          "sha1": "905d3953ef9d5646252694a9c43bc0f66807df18",
          "md5": "53dd62e3afa1f35d706a28b2a3ba3773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.1.jar",
          "url": "versiont-toolchain-1.3.1.jar",
          "size": 27465,
          "sha512": "4ec25a6d17e6a714c848dbbf4950451fee3ebf74af45312080a87a9c43e03b1a48c31a746434b82852776fa757b9cabc2246c16e8e1309e6fed461f7783fb9a0",
          "sha256": "c332efe2c4f9b600e56964e59c683be1209f8b342798bbc48cfc5eef7cfd5d6d",
          "sha1": "905d3953ef9d5646252694a9c43bc0f66807df18",
          "md5": "53dd62e3afa1f35d706a28b2a3ba3773"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.1-javadoc.jar",
          "url": "versiont-toolchain-1.3.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versiont-toolchain-1.3.1-sources.jar",
          "url": "versiont-toolchain-1.3.1-sources.jar",
          "size": 8352,
          "sha512": "6ea04e38c823f909d691862e6c20c62bb32a0f86c03046b3f415ac4acae00ee9bfc26ebdda6735221e7f97ed2d4444d973702083ad29d57cdbf069bcaa04af94",
          "sha256": "726ec6a78784ae238b9ce9c5865cd4eeba2d76560b9a4674a1c9b9123b0dd575",
          "sha1": "bc589e4992ddcc037fe5c7a940a7438b74ead5aa",
          "md5": "1f8fccc881f4d669ab70fbb494aed65a"
        }
      ]
    }
  ]
}
